import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';

// const inter = Inter({ subsets: ['latin'] });
const poppins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>
      <body className={poppins.className} >
        <div className="w-full flex items-center justify-center flex-col max-w-full overflow-x-hidden">
          <Header />
          <main className="flex flex-1 flex-col w-full min-h-screen py-20 bg-slate-200">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
